//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentGatewayTestingTool.EzidebitPCI {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EziResponseOfstring", Namespace="https://px.ezidebit.com.au/")]
    [System.SerializableAttribute()]
    public partial class EziResponseOfstring : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EziResponseOfString", Namespace="https://px.ezidebit.com.au/")]
    [System.SerializableAttribute()]
    public partial class EziResponseOfString1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EziResponseOfNewCustomerXcXH3liW", Namespace="https://px.ezidebit.com.au/")]
    [System.SerializableAttribute()]
    public partial class EziResponseOfNewCustomerXcXH3liW : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PaymentGatewayTestingTool.EzidebitPCI.NewCustomer DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PaymentGatewayTestingTool.EzidebitPCI.NewCustomer Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewCustomer", Namespace="http://schemas.datacontract.org/2004/07/Ezidebit.PaymentExchange.V3_3.DataContrac" +
        "ts")]
    [System.SerializableAttribute()]
    public partial class NewCustomer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerRefField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerRef {
            get {
                return this.CustomerRefField;
            }
            set {
                if ((this.CustomerRefField.Equals(value) != true)) {
                    this.CustomerRefField = value;
                    this.RaisePropertyChanged("CustomerRef");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EziResponseOfRealtimePaymentResponseTHgMB7oL", Namespace="https://px.ezidebit.com.au/")]
    [System.SerializableAttribute()]
    public partial class EziResponseOfRealtimePaymentResponseTHgMB7oL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PaymentGatewayTestingTool.EzidebitPCI.RealtimePaymentResponse DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PaymentGatewayTestingTool.EzidebitPCI.RealtimePaymentResponse Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RealtimePaymentResponse", Namespace="https://px.ezidebit.com.au/")]
    [System.SerializableAttribute()]
    public partial class RealtimePaymentResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankReceiptIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExchangePaymentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentResultTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankReceiptID {
            get {
                return this.BankReceiptIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BankReceiptIDField, value) != true)) {
                    this.BankReceiptIDField = value;
                    this.RaisePropertyChanged("BankReceiptID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExchangePaymentID {
            get {
                return this.ExchangePaymentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ExchangePaymentIDField, value) != true)) {
                    this.ExchangePaymentIDField = value;
                    this.RaisePropertyChanged("ExchangePaymentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentResult {
            get {
                return this.PaymentResultField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentResultField, value) != true)) {
                    this.PaymentResultField = value;
                    this.RaisePropertyChanged("PaymentResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentResultCode {
            get {
                return this.PaymentResultCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentResultCodeField, value) != true)) {
                    this.PaymentResultCodeField = value;
                    this.RaisePropertyChanged("PaymentResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentResultText {
            get {
                return this.PaymentResultTextField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentResultTextField, value) != true)) {
                    this.PaymentResultTextField = value;
                    this.RaisePropertyChanged("PaymentResultText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EziResponseOfAccountDetailsTHgMB7oL", Namespace="https://px.ezidebit.com.au/")]
    [System.SerializableAttribute()]
    public partial class EziResponseOfAccountDetailsTHgMB7oL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PaymentGatewayTestingTool.EzidebitPCI.AccountDetails DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PaymentGatewayTestingTool.EzidebitPCI.AccountDetails Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountDetails", Namespace="https://px.ezidebit.com.au/")]
    [System.SerializableAttribute()]
    public partial class AccountDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountHolderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BSBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardHolderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditCardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExpiryMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExpiryYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentMethodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountHolderName {
            get {
                return this.AccountHolderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountHolderNameField, value) != true)) {
                    this.AccountHolderNameField = value;
                    this.RaisePropertyChanged("AccountHolderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BSB {
            get {
                return this.BSBField;
            }
            set {
                if ((object.ReferenceEquals(this.BSBField, value) != true)) {
                    this.BSBField = value;
                    this.RaisePropertyChanged("BSB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardHolderName {
            get {
                return this.CardHolderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardHolderNameField, value) != true)) {
                    this.CardHolderNameField = value;
                    this.RaisePropertyChanged("CardHolderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditCardNumber {
            get {
                return this.CreditCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditCardNumberField, value) != true)) {
                    this.CreditCardNumberField = value;
                    this.RaisePropertyChanged("CreditCardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExpiryMonth {
            get {
                return this.ExpiryMonthField;
            }
            set {
                if ((this.ExpiryMonthField.Equals(value) != true)) {
                    this.ExpiryMonthField = value;
                    this.RaisePropertyChanged("ExpiryMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExpiryYear {
            get {
                return this.ExpiryYearField;
            }
            set {
                if ((this.ExpiryYearField.Equals(value) != true)) {
                    this.ExpiryYearField = value;
                    this.RaisePropertyChanged("ExpiryYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentMethod {
            get {
                return this.PaymentMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentMethodField, value) != true)) {
                    this.PaymentMethodField = value;
                    this.RaisePropertyChanged("PaymentMethod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://px.ezidebit.com.au/", ConfigurationName="EzidebitPCI.IPCIService")]
    public interface IPCIService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/IPCIService/EditCustomerBankAccount", ReplyAction="https://px.ezidebit.com.au/IPCIService/EditCustomerBankAccountResponse")]
        PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfstring EditCustomerBankAccount(string DigitalKey, string EziDebitCustomerID, string YourSystemReference, string BankAccountName, string BankAccountBSB, string BankAccountNumber, string Reactivate, string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/IPCIService/EditCustomerBankAccount", ReplyAction="https://px.ezidebit.com.au/IPCIService/EditCustomerBankAccountResponse")]
        System.Threading.Tasks.Task<PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfstring> EditCustomerBankAccountAsync(string DigitalKey, string EziDebitCustomerID, string YourSystemReference, string BankAccountName, string BankAccountBSB, string BankAccountNumber, string Reactivate, string Username);
        
        // CODEGEN: Generating message contract since element name DigitalKey from namespace https://px.ezidebit.com.au/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/IPCIService/EditCustomerCreditCard", ReplyAction="https://px.ezidebit.com.au/IPCIService/EditCustomerCreditCardResponse")]
        PaymentGatewayTestingTool.EzidebitPCI.EditCustomerCreditCardResponse EditCustomerCreditCard(PaymentGatewayTestingTool.EzidebitPCI.EditCustomerCreditCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/IPCIService/EditCustomerCreditCard", ReplyAction="https://px.ezidebit.com.au/IPCIService/EditCustomerCreditCardResponse")]
        System.Threading.Tasks.Task<PaymentGatewayTestingTool.EzidebitPCI.EditCustomerCreditCardResponse> EditCustomerCreditCardAsync(PaymentGatewayTestingTool.EzidebitPCI.EditCustomerCreditCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/IPCIService/AddCardDebit", ReplyAction="https://px.ezidebit.com.au/IPCIService/AddCardDebitResponse")]
        PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfNewCustomerXcXH3liW AddCardDebit(
                    string DigitalKey, 
                    string YourSystemReference, 
                    string YourGeneralReference, 
                    string LastName, 
                    string FirstName, 
                    string EmailAddress, 
                    string MobilePhoneNumber, 
                    string PaymentReference, 
                    string NameOnCreditCard, 
                    string CreditCardNumber, 
                    int CreditCardExpiryYear, 
                    int CreditCardExpiryMonth, 
                    long PaymentAmountInCents, 
                    string DebitDate, 
                    string SmsPaymentReminder, 
                    string SmsFailedNotification, 
                    string SmsExpiredCard, 
                    string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/IPCIService/AddCardDebit", ReplyAction="https://px.ezidebit.com.au/IPCIService/AddCardDebitResponse")]
        System.Threading.Tasks.Task<PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfNewCustomerXcXH3liW> AddCardDebitAsync(
                    string DigitalKey, 
                    string YourSystemReference, 
                    string YourGeneralReference, 
                    string LastName, 
                    string FirstName, 
                    string EmailAddress, 
                    string MobilePhoneNumber, 
                    string PaymentReference, 
                    string NameOnCreditCard, 
                    string CreditCardNumber, 
                    int CreditCardExpiryYear, 
                    int CreditCardExpiryMonth, 
                    long PaymentAmountInCents, 
                    string DebitDate, 
                    string SmsPaymentReminder, 
                    string SmsFailedNotification, 
                    string SmsExpiredCard, 
                    string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/IPCIService/AddBankDebit", ReplyAction="https://px.ezidebit.com.au/IPCIService/AddBankDebitResponse")]
        PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfNewCustomerXcXH3liW AddBankDebit(
                    string DigitalKey, 
                    string YourSystemReference, 
                    string YourGeneralReference, 
                    string LastName, 
                    string FirstName, 
                    string EmailAddress, 
                    string MobilePhoneNumber, 
                    string PaymentReference, 
                    string BankAccountName, 
                    string BankAccountBSB, 
                    string BankAccountNumber, 
                    long PaymentAmountInCents, 
                    string DebitDate, 
                    string SmsPaymentReminder, 
                    string SmsFailedNotification, 
                    string SmsExpiredCard, 
                    string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/IPCIService/AddBankDebit", ReplyAction="https://px.ezidebit.com.au/IPCIService/AddBankDebitResponse")]
        System.Threading.Tasks.Task<PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfNewCustomerXcXH3liW> AddBankDebitAsync(
                    string DigitalKey, 
                    string YourSystemReference, 
                    string YourGeneralReference, 
                    string LastName, 
                    string FirstName, 
                    string EmailAddress, 
                    string MobilePhoneNumber, 
                    string PaymentReference, 
                    string BankAccountName, 
                    string BankAccountBSB, 
                    string BankAccountNumber, 
                    long PaymentAmountInCents, 
                    string DebitDate, 
                    string SmsPaymentReminder, 
                    string SmsFailedNotification, 
                    string SmsExpiredCard, 
                    string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/IPCIService/ProcessRealtimeCreditCardPayment", ReplyAction="https://px.ezidebit.com.au/IPCIService/ProcessRealtimeCreditCardPaymentResponse")]
        PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfRealtimePaymentResponseTHgMB7oL ProcessRealtimeCreditCardPayment(string DigitalKey, string CreditCardNumber, string CreditCardExpiryMonth, string CreditCardExpiryYear, string CreditCardCCV, string NameOnCreditCard, long PaymentAmountInCents, string CustomerName, string PaymentReference);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/IPCIService/ProcessRealtimeCreditCardPayment", ReplyAction="https://px.ezidebit.com.au/IPCIService/ProcessRealtimeCreditCardPaymentResponse")]
        System.Threading.Tasks.Task<PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfRealtimePaymentResponseTHgMB7oL> ProcessRealtimeCreditCardPaymentAsync(string DigitalKey, string CreditCardNumber, string CreditCardExpiryMonth, string CreditCardExpiryYear, string CreditCardCCV, string NameOnCreditCard, long PaymentAmountInCents, string CustomerName, string PaymentReference);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/IPCIService/GetCustomerAccountDetails", ReplyAction="https://px.ezidebit.com.au/IPCIService/GetCustomerAccountDetailsResponse")]
        PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfAccountDetailsTHgMB7oL GetCustomerAccountDetails(string DigitalKey, string EzidebitCustomerID, string YourSystemReference);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/IPCIService/GetCustomerAccountDetails", ReplyAction="https://px.ezidebit.com.au/IPCIService/GetCustomerAccountDetailsResponse")]
        System.Threading.Tasks.Task<PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfAccountDetailsTHgMB7oL> GetCustomerAccountDetailsAsync(string DigitalKey, string EzidebitCustomerID, string YourSystemReference);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/IPCIService/ProcessRealtimeTokenPayment", ReplyAction="https://px.ezidebit.com.au/IPCIService/ProcessRealtimeTokenPaymentResponse")]
        PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfRealtimePaymentResponseTHgMB7oL ProcessRealtimeTokenPayment(string digitalKey, string token, long paymentAmountInCents, string customerName, string paymentReference);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/IPCIService/ProcessRealtimeTokenPayment", ReplyAction="https://px.ezidebit.com.au/IPCIService/ProcessRealtimeTokenPaymentResponse")]
        System.Threading.Tasks.Task<PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfRealtimePaymentResponseTHgMB7oL> ProcessRealtimeTokenPaymentAsync(string digitalKey, string token, long paymentAmountInCents, string customerName, string paymentReference);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/IPCIService/TestFunction", ReplyAction="https://px.ezidebit.com.au/IPCIService/TestFunctionResponse")]
        PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfstring TestFunction(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/IPCIService/TestFunction", ReplyAction="https://px.ezidebit.com.au/IPCIService/TestFunctionResponse")]
        System.Threading.Tasks.Task<PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfstring> TestFunctionAsync(string input);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditCustomerCreditCardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditCustomerCreditCard", Namespace="https://px.ezidebit.com.au/", Order=0)]
        public PaymentGatewayTestingTool.EzidebitPCI.EditCustomerCreditCardRequestBody Body;
        
        public EditCustomerCreditCardRequest() {
        }
        
        public EditCustomerCreditCardRequest(PaymentGatewayTestingTool.EzidebitPCI.EditCustomerCreditCardRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://px.ezidebit.com.au/")]
    public partial class EditCustomerCreditCardRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DigitalKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EziDebitCustomerID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string YourSystemReference;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NameOnCreditCard;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CreditCardNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int CreditCardExpiryYear;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int CreditCardExpiryMonth;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Reactivate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Username;
        
        public EditCustomerCreditCardRequestBody() {
        }
        
        public EditCustomerCreditCardRequestBody(string DigitalKey, string EziDebitCustomerID, string YourSystemReference, string NameOnCreditCard, string CreditCardNumber, int CreditCardExpiryYear, int CreditCardExpiryMonth, string Reactivate, string Username) {
            this.DigitalKey = DigitalKey;
            this.EziDebitCustomerID = EziDebitCustomerID;
            this.YourSystemReference = YourSystemReference;
            this.NameOnCreditCard = NameOnCreditCard;
            this.CreditCardNumber = CreditCardNumber;
            this.CreditCardExpiryYear = CreditCardExpiryYear;
            this.CreditCardExpiryMonth = CreditCardExpiryMonth;
            this.Reactivate = Reactivate;
            this.Username = Username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditCustomerCreditCardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditCustomerCreditCardResponse", Namespace="https://px.ezidebit.com.au/", Order=0)]
        public PaymentGatewayTestingTool.EzidebitPCI.EditCustomerCreditCardResponseBody Body;
        
        public EditCustomerCreditCardResponse() {
        }
        
        public EditCustomerCreditCardResponse(PaymentGatewayTestingTool.EzidebitPCI.EditCustomerCreditCardResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://px.ezidebit.com.au/")]
    public partial class EditCustomerCreditCardResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfString1 EditCustomerCreditCardResult;
        
        public EditCustomerCreditCardResponseBody() {
        }
        
        public EditCustomerCreditCardResponseBody(PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfString1 EditCustomerCreditCardResult) {
            this.EditCustomerCreditCardResult = EditCustomerCreditCardResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPCIServiceChannel : PaymentGatewayTestingTool.EzidebitPCI.IPCIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PCIServiceClient : System.ServiceModel.ClientBase<PaymentGatewayTestingTool.EzidebitPCI.IPCIService>, PaymentGatewayTestingTool.EzidebitPCI.IPCIService {
        
        public PCIServiceClient() {
        }
        
        public PCIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PCIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PCIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PCIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfstring EditCustomerBankAccount(string DigitalKey, string EziDebitCustomerID, string YourSystemReference, string BankAccountName, string BankAccountBSB, string BankAccountNumber, string Reactivate, string Username) {
            return base.Channel.EditCustomerBankAccount(DigitalKey, EziDebitCustomerID, YourSystemReference, BankAccountName, BankAccountBSB, BankAccountNumber, Reactivate, Username);
        }
        
        public System.Threading.Tasks.Task<PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfstring> EditCustomerBankAccountAsync(string DigitalKey, string EziDebitCustomerID, string YourSystemReference, string BankAccountName, string BankAccountBSB, string BankAccountNumber, string Reactivate, string Username) {
            return base.Channel.EditCustomerBankAccountAsync(DigitalKey, EziDebitCustomerID, YourSystemReference, BankAccountName, BankAccountBSB, BankAccountNumber, Reactivate, Username);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PaymentGatewayTestingTool.EzidebitPCI.EditCustomerCreditCardResponse PaymentGatewayTestingTool.EzidebitPCI.IPCIService.EditCustomerCreditCard(PaymentGatewayTestingTool.EzidebitPCI.EditCustomerCreditCardRequest request) {
            return base.Channel.EditCustomerCreditCard(request);
        }
        
        public PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfString1 EditCustomerCreditCard(string DigitalKey, string EziDebitCustomerID, string YourSystemReference, string NameOnCreditCard, string CreditCardNumber, int CreditCardExpiryYear, int CreditCardExpiryMonth, string Reactivate, string Username) {
            PaymentGatewayTestingTool.EzidebitPCI.EditCustomerCreditCardRequest inValue = new PaymentGatewayTestingTool.EzidebitPCI.EditCustomerCreditCardRequest();
            inValue.Body = new PaymentGatewayTestingTool.EzidebitPCI.EditCustomerCreditCardRequestBody();
            inValue.Body.DigitalKey = DigitalKey;
            inValue.Body.EziDebitCustomerID = EziDebitCustomerID;
            inValue.Body.YourSystemReference = YourSystemReference;
            inValue.Body.NameOnCreditCard = NameOnCreditCard;
            inValue.Body.CreditCardNumber = CreditCardNumber;
            inValue.Body.CreditCardExpiryYear = CreditCardExpiryYear;
            inValue.Body.CreditCardExpiryMonth = CreditCardExpiryMonth;
            inValue.Body.Reactivate = Reactivate;
            inValue.Body.Username = Username;
            PaymentGatewayTestingTool.EzidebitPCI.EditCustomerCreditCardResponse retVal = ((PaymentGatewayTestingTool.EzidebitPCI.IPCIService)(this)).EditCustomerCreditCard(inValue);
            return retVal.Body.EditCustomerCreditCardResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PaymentGatewayTestingTool.EzidebitPCI.EditCustomerCreditCardResponse> PaymentGatewayTestingTool.EzidebitPCI.IPCIService.EditCustomerCreditCardAsync(PaymentGatewayTestingTool.EzidebitPCI.EditCustomerCreditCardRequest request) {
            return base.Channel.EditCustomerCreditCardAsync(request);
        }
        
        public System.Threading.Tasks.Task<PaymentGatewayTestingTool.EzidebitPCI.EditCustomerCreditCardResponse> EditCustomerCreditCardAsync(string DigitalKey, string EziDebitCustomerID, string YourSystemReference, string NameOnCreditCard, string CreditCardNumber, int CreditCardExpiryYear, int CreditCardExpiryMonth, string Reactivate, string Username) {
            PaymentGatewayTestingTool.EzidebitPCI.EditCustomerCreditCardRequest inValue = new PaymentGatewayTestingTool.EzidebitPCI.EditCustomerCreditCardRequest();
            inValue.Body = new PaymentGatewayTestingTool.EzidebitPCI.EditCustomerCreditCardRequestBody();
            inValue.Body.DigitalKey = DigitalKey;
            inValue.Body.EziDebitCustomerID = EziDebitCustomerID;
            inValue.Body.YourSystemReference = YourSystemReference;
            inValue.Body.NameOnCreditCard = NameOnCreditCard;
            inValue.Body.CreditCardNumber = CreditCardNumber;
            inValue.Body.CreditCardExpiryYear = CreditCardExpiryYear;
            inValue.Body.CreditCardExpiryMonth = CreditCardExpiryMonth;
            inValue.Body.Reactivate = Reactivate;
            inValue.Body.Username = Username;
            return ((PaymentGatewayTestingTool.EzidebitPCI.IPCIService)(this)).EditCustomerCreditCardAsync(inValue);
        }
        
        public PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfNewCustomerXcXH3liW AddCardDebit(
                    string DigitalKey, 
                    string YourSystemReference, 
                    string YourGeneralReference, 
                    string LastName, 
                    string FirstName, 
                    string EmailAddress, 
                    string MobilePhoneNumber, 
                    string PaymentReference, 
                    string NameOnCreditCard, 
                    string CreditCardNumber, 
                    int CreditCardExpiryYear, 
                    int CreditCardExpiryMonth, 
                    long PaymentAmountInCents, 
                    string DebitDate, 
                    string SmsPaymentReminder, 
                    string SmsFailedNotification, 
                    string SmsExpiredCard, 
                    string Username) {
            return base.Channel.AddCardDebit(DigitalKey, YourSystemReference, YourGeneralReference, LastName, FirstName, EmailAddress, MobilePhoneNumber, PaymentReference, NameOnCreditCard, CreditCardNumber, CreditCardExpiryYear, CreditCardExpiryMonth, PaymentAmountInCents, DebitDate, SmsPaymentReminder, SmsFailedNotification, SmsExpiredCard, Username);
        }
        
        public System.Threading.Tasks.Task<PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfNewCustomerXcXH3liW> AddCardDebitAsync(
                    string DigitalKey, 
                    string YourSystemReference, 
                    string YourGeneralReference, 
                    string LastName, 
                    string FirstName, 
                    string EmailAddress, 
                    string MobilePhoneNumber, 
                    string PaymentReference, 
                    string NameOnCreditCard, 
                    string CreditCardNumber, 
                    int CreditCardExpiryYear, 
                    int CreditCardExpiryMonth, 
                    long PaymentAmountInCents, 
                    string DebitDate, 
                    string SmsPaymentReminder, 
                    string SmsFailedNotification, 
                    string SmsExpiredCard, 
                    string Username) {
            return base.Channel.AddCardDebitAsync(DigitalKey, YourSystemReference, YourGeneralReference, LastName, FirstName, EmailAddress, MobilePhoneNumber, PaymentReference, NameOnCreditCard, CreditCardNumber, CreditCardExpiryYear, CreditCardExpiryMonth, PaymentAmountInCents, DebitDate, SmsPaymentReminder, SmsFailedNotification, SmsExpiredCard, Username);
        }
        
        public PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfNewCustomerXcXH3liW AddBankDebit(
                    string DigitalKey, 
                    string YourSystemReference, 
                    string YourGeneralReference, 
                    string LastName, 
                    string FirstName, 
                    string EmailAddress, 
                    string MobilePhoneNumber, 
                    string PaymentReference, 
                    string BankAccountName, 
                    string BankAccountBSB, 
                    string BankAccountNumber, 
                    long PaymentAmountInCents, 
                    string DebitDate, 
                    string SmsPaymentReminder, 
                    string SmsFailedNotification, 
                    string SmsExpiredCard, 
                    string Username) {
            return base.Channel.AddBankDebit(DigitalKey, YourSystemReference, YourGeneralReference, LastName, FirstName, EmailAddress, MobilePhoneNumber, PaymentReference, BankAccountName, BankAccountBSB, BankAccountNumber, PaymentAmountInCents, DebitDate, SmsPaymentReminder, SmsFailedNotification, SmsExpiredCard, Username);
        }
        
        public System.Threading.Tasks.Task<PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfNewCustomerXcXH3liW> AddBankDebitAsync(
                    string DigitalKey, 
                    string YourSystemReference, 
                    string YourGeneralReference, 
                    string LastName, 
                    string FirstName, 
                    string EmailAddress, 
                    string MobilePhoneNumber, 
                    string PaymentReference, 
                    string BankAccountName, 
                    string BankAccountBSB, 
                    string BankAccountNumber, 
                    long PaymentAmountInCents, 
                    string DebitDate, 
                    string SmsPaymentReminder, 
                    string SmsFailedNotification, 
                    string SmsExpiredCard, 
                    string Username) {
            return base.Channel.AddBankDebitAsync(DigitalKey, YourSystemReference, YourGeneralReference, LastName, FirstName, EmailAddress, MobilePhoneNumber, PaymentReference, BankAccountName, BankAccountBSB, BankAccountNumber, PaymentAmountInCents, DebitDate, SmsPaymentReminder, SmsFailedNotification, SmsExpiredCard, Username);
        }
        
        public PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfRealtimePaymentResponseTHgMB7oL ProcessRealtimeCreditCardPayment(string DigitalKey, string CreditCardNumber, string CreditCardExpiryMonth, string CreditCardExpiryYear, string CreditCardCCV, string NameOnCreditCard, long PaymentAmountInCents, string CustomerName, string PaymentReference) {
            return base.Channel.ProcessRealtimeCreditCardPayment(DigitalKey, CreditCardNumber, CreditCardExpiryMonth, CreditCardExpiryYear, CreditCardCCV, NameOnCreditCard, PaymentAmountInCents, CustomerName, PaymentReference);
        }
        
        public System.Threading.Tasks.Task<PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfRealtimePaymentResponseTHgMB7oL> ProcessRealtimeCreditCardPaymentAsync(string DigitalKey, string CreditCardNumber, string CreditCardExpiryMonth, string CreditCardExpiryYear, string CreditCardCCV, string NameOnCreditCard, long PaymentAmountInCents, string CustomerName, string PaymentReference) {
            return base.Channel.ProcessRealtimeCreditCardPaymentAsync(DigitalKey, CreditCardNumber, CreditCardExpiryMonth, CreditCardExpiryYear, CreditCardCCV, NameOnCreditCard, PaymentAmountInCents, CustomerName, PaymentReference);
        }
        
        public PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfAccountDetailsTHgMB7oL GetCustomerAccountDetails(string DigitalKey, string EzidebitCustomerID, string YourSystemReference) {
            return base.Channel.GetCustomerAccountDetails(DigitalKey, EzidebitCustomerID, YourSystemReference);
        }
        
        public System.Threading.Tasks.Task<PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfAccountDetailsTHgMB7oL> GetCustomerAccountDetailsAsync(string DigitalKey, string EzidebitCustomerID, string YourSystemReference) {
            return base.Channel.GetCustomerAccountDetailsAsync(DigitalKey, EzidebitCustomerID, YourSystemReference);
        }
        
        public PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfRealtimePaymentResponseTHgMB7oL ProcessRealtimeTokenPayment(string digitalKey, string token, long paymentAmountInCents, string customerName, string paymentReference) {
            return base.Channel.ProcessRealtimeTokenPayment(digitalKey, token, paymentAmountInCents, customerName, paymentReference);
        }
        
        public System.Threading.Tasks.Task<PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfRealtimePaymentResponseTHgMB7oL> ProcessRealtimeTokenPaymentAsync(string digitalKey, string token, long paymentAmountInCents, string customerName, string paymentReference) {
            return base.Channel.ProcessRealtimeTokenPaymentAsync(digitalKey, token, paymentAmountInCents, customerName, paymentReference);
        }
        
        public PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfstring TestFunction(string input) {
            return base.Channel.TestFunction(input);
        }
        
        public System.Threading.Tasks.Task<PaymentGatewayTestingTool.EzidebitPCI.EziResponseOfstring> TestFunctionAsync(string input) {
            return base.Channel.TestFunctionAsync(input);
        }
    }
}
